
module.exports = async function (req, res) {
  // CORS Headers
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
  );

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  try {
    console.log(`[API] Start. Node: ${process.version}`);
    
    // 1. Check API Key
    const apiKey = process.env.API_KEY;
    if (!apiKey) {
      console.error("[API] Error: API_KEY is missing in env.");
      return res.status(500).json({ error: 'Server Config Error: API_KEY missing' });
    }

    // 2. Safe Dynamic Import
    let GoogleGenAI;
    try {
      const module = await import("@google/genai");
      GoogleGenAI = module.GoogleGenAI;
    } catch (importError) {
      console.error("[API] Failed to import @google/genai:", importError);
      return res.status(500).json({ 
        error: 'Failed to load AI SDK', 
        details: importError.message 
      });
    }

    // 3. Initialize AI
    const ai = new GoogleGenAI({ apiKey: apiKey });
    const { action, payload } = req.body;

    console.log(`[API] Action: ${action}`);

    // Action Handlers
    if (action === 'generateContent') {
      const { model, contents, config } = payload;
      const response = await ai.models.generateContent({ model, contents, config });
      return res.status(200).json({ text: response.text });
    }
    
    else if (action === 'generateImages') {
      const { model, prompt, config } = payload;
      
      if (model.includes('imagen')) {
         const response = await ai.models.generateImages({ model, prompt, config });
         const b64 = response.generatedImages?.[0]?.image?.imageBytes;
         return res.status(200).json({ base64: b64 });
      } else {
         const response = await ai.models.generateContent({
             model,
             contents: { parts: [{ text: prompt }] },
             config
         });
         
         let b64 = null;
         for (const part of response.candidates?.[0]?.content?.parts || []) {
            if (part.inlineData) {
                b64 = part.inlineData.data;
                break;
            }
         }
         
         if (!b64) throw new Error("No image generated by model");
         return res.status(200).json({ base64: b64 });
      }
    }
    
    else if (action === 'generateVideos') {
       const { model, prompt, config } = payload;
       let operation = await ai.models.generateVideos({ model, prompt, config });

       // Polling (Max 60s)
       let attempts = 0;
       while (!operation.done && attempts < 20) { 
           await new Promise(r => setTimeout(r, 3000));
           operation = await ai.operations.getVideosOperation({ operation: operation });
           attempts++;
       }

       if (!operation.done) {
           return res.status(408).json({ error: "Video generation timed out (Vercel limit)." });
       }

       const videoUri = operation.response?.generatedVideos?.[0]?.video?.uri;
       if (!videoUri) throw new Error("No video URI returned");

       const downloadUrl = `${videoUri}&key=${apiKey}`;
       const videoRes = await fetch(downloadUrl);
       if (!videoRes.ok) throw new Error("Failed to download video from Google");
       
       const arrayBuffer = await videoRes.arrayBuffer();
       const base64Video = Buffer.from(arrayBuffer).toString('base64');

       return res.status(200).json({ videoBase64: base64Video });
    }

    else {
        return res.status(400).json({ error: `Unknown action: ${action}` });
    }

  } catch (error) {
    console.error('[API Critical Error]:', error);
    // Return JSON even on crash
    return res.status(500).json({ 
        error: error.message || 'Internal Server Error',
        stack: error.stack 
    });
  }
};
